# Generated by Django 5.2.14 on 2026-05-08 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('timing', models.CharField(blank=True, help_text='e.g. 9:00 AM - 11:00 AM', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('duration', models.CharField(blank=True, help_text='e.g. 3 Months, 6 Months', max_length=50)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='students/signatures/')),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('course_interested', models.CharField(max_length=100)),
                ('reference', models.CharField(choices=[('friend', 'Friend'), ('social_media', 'Social Media'), ('advertisement', 'Advertisement'), ('school', 'School'), ('coaching', 'Coaching'), ('other', 'Other')], default='friend', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('followup', 'Follow Up'), ('converted', 'Converted'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('enquiry_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries_added', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='core.student')),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-enquiry_date'],
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField()),
                ('total_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_added', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='core.batch')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='core.course')),
                ('enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='core.enquiry')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='core.student')),
            ],
            options={
                'ordering': ['-admission_date'],
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('course_name', models.CharField(max_length=100)),
                ('payment_type', models.CharField(choices=[('full', 'Full Payment'), ('installment', 'Installment')], default='full', max_length=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_records', to='core.admission')),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees_collected', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Fees',
                'ordering': ['-payment_date'],
            },
        ),
    ]
